USE Membership

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME=N'Member')
BEGIN
CREATE TABLE Member (
						Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
						Name NVARCHAR(50) NOT NULL,
						Age INT NOT NULL,
						Address NVARCHAR(50) NOT NULL,
						Contact NVARCHAR(15) NOT NULL,
						Gender NVARCHAR(15) NOT NULL,
						DOB NVARCHAR(20) NOT NULL
					)
END
