USE Membership
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Library ') 
BEGIN
	CREATE TABLE Library (LibraryId INT PRIMARY KEY IDENTITY NOT NULL,
					  Department NVARCHAR(50) NOT NULL)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Student ')
BEGIN						
	CREATE TABLE Student (StudentId INT PRIMARY KEY IDENTITY NOT NULL,
						Name NVARCHAR(50) NOT NULL,
						LibraryId INT NOT NULL FOREIGN KEY REFERENCES Library(LibraryId))

END

INSERT INTO Library (Department) VALUES('Comic'),('Melody')
INSERT INTO Student (Name,LibraryId) VALUES('Test',1)					